### PR TITLE
OWGeoMap PyQt5 fixup

### PR DESCRIPTION
**Pull request by nikicc**
WebEngine in PyQt 5.7.0 does not allow to open local contetn from html files due to a bug (https://bugreports.qt.io/browse/QTBUG-55902).

Needs testing on PyQt4.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Most things work ok with GeoMap. The only proper issue I've found is that selection is not sent onwards with PyQt4. It works in PyQt5, though...

As a note to the side, with 'Locations' attribute for NY Times, sometimes you get a result:
Ljubljana (Slovenia), Slovenia, Europe (Slovenia),
which would could Slovenia 3 times instead of once, Is there a good way to solve this? One solution would be a checkbox says 'count once if in text', but I'd prefer to avoid checkboxes if possible.

**Comment by nikicc** [comment]
@ajdapretnar the current version should also work with PyQt4.

**Comment by nikicc** [comment]
Regarding the side note, it can be fixed separately. I opened an issue about this.

**Comment by ajdapretnar** [comment]
This looks good on both PyQt4 and PyQt5. Tested, so I'm merging.

**Pull request merged**
