### PR TITLE
Output corresponding duplicate cluster

### LINKED ISSUE #378: Duplicate Detection: output cluster, not first instance
##### Text version

0.5.0

##### Orange version

3.16.dev

##### Expected behavior
Duplicate Cluster outputs duplicate documents.

##### Actual behavior
Duplicate Cluster outputs the first document in a corpus.

##### Steps to reproduce the behavior
Corpus - Bag of Words - Distances - Duplicate Detection. Regardless of which cluster you select, the output will always be the first document of a corpus.

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue
Fixes #378. 

##### Description of changes
Detect Duplicates now outputs correct documents with Duplicate Cluster output.

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by robertcv** [comment]
Looks good, could you just add a new line on the end of the test.

**Comment by ajdapretnar** [comment]
We discussed with @lanzagar to solve this in a nicer way. `int(cluster[1:])` is really not all that elegant and not very future-proof. I need to figure out how to retrieve just the cluster number and not cast strings to ints. Suggestions welcome. I honestly think this widget should be re-done in parts as some instances are duplicated. I would be nice if we can work with a simple dict and use it for everything.

**Comment by ajdapretnar** [comment]
@robertcv this is ready for another review and potential merge.

**Comment by robertcv** [comment]
I produced an error by deselecting the selected cluster in Duplicate Cluster widget. This needs to be handled before I merge.

**Comment by ajdapretnar** [comment]
Fixed. I also added a test to prevent future errors. :) 💪

**Pull request merged**
