### PR TITLE
BoW Support Storing & Loading a Classifier

### PR DESCRIPTION
**Pull request by nikicc**
This PR enables storing a classifier trained on BoW data and then loading and applying it on new data. The new data should not be preprocessed or vectorized since feature's compute values will preprocess and vectorize the new data in the same way as it was done when learning a classifier.

One problem still persist:
* When the data contains some features in X, the BoW model on new data will be dense. This is the consequence of `Table.from_table` retaining the initial sparsity structure of arrays.

### CODE REVIEW

**Comment by nikicc** [comment]
@ajdapretnar this is ready for some testing. @kernc could you also take a look?

**Comment by ajdapretnar** [comment]
@nikicc This breaks some stuff seriously. Just loading bookexcerpts in Corpus and putting it in a Data Table everything crashes and I'm getting constant errors (had to force-kill the process).

**Comment by nikicc** [comment]
@ajdapretnar https://github.com/biolab/orange3/pull/1675 should fix these problems.

**Comment by ajdapretnar** [comment]
So far so good. https://github.com/biolab/orange3/pull/1675 seems to indeed fix the problem and storing the classifier works well. However, I seemed to have forgotten Load Classifier only works with Predictions. Any reason for that?

**Comment by nikicc** [comment]
> However, I seemed to have forgotten Load Classifier only works with Predictions. Any reason for that?

Whit which other widgets would you expect it to work besides Predictions?

**Comment by ajdapretnar** [comment]
No, never mind, I got lost in tracking several conversations. Doesn't apply. :)

**Comment by kernc** [comment]
> With which other widgets would you expect it to work besides Predictions?

_Test and **Score**_.

**Comment by ajdapretnar** [comment]
Ok, I'm merging this as it works and it is great, we can discuss Load Classifier later.

**Comment by nikicc** [comment]
> Test and **Score**.

It would be nice, if one could also pass classifiers into Test & Score. Then, you could, for example score the performance of already trained models on new test data.

**Pull request merged**
