### PR TITLE
fixed ZeroDivisionError on line 233 in perc_unique

### PR DESCRIPTION
**Pull request by priyanshu-bisht**
##### Issue
- Statistics: division by zero #573

##### Description of changes
- fixed the bug on line 233 (function perc_unique) in orangecontrib/text/widgets/owstatistics.py

- _Included_ conditional check of the tokens

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Thank you for your contribution.

I have two comments.
1. Would you mind squashing your commits so that the PR is cleaner?
```
git rebase -i master
# fixup the second commit
git push -f origin master
```
2. Such fixes deserve a corresponding test. Would you mind submitting it? In `test_owstatistics` on line 173.

Thank you!

**Comment by priyanshu-bisht** [comment]
@ajdapretnar 
Yes would rebase the commits :)
And I'm having trouble with understanding the testing part, could you guide me through please, thanks!

**Comment by priyanshu-bisht** [comment]
@janezd 
Yes that all cool, I love learning new things
Would make the changes asap :)

**Comment by janezd** [comment]
> And I'm having trouble with understanding the testing part, could you guide me through please, thanks!

There's nothing to guide you through, actually. When you make a pull request or add a commit, tests are automatically run. Orange is large and tests sometimes fail for no apparent reason; we assume it's related to things we do wrong when testing with Qt, but it's impossible to trace and debug. So if tests fail, especially if just one fails and others pass, we just restart them. For some reason, I couldn't do this on this repo, and you probably can't, because you have no admin privileges. The solution in this case is to run `git commit --amend`, change nothing, and then `git push -f`. (Amend is needed to make git believe that you've changed something, so there is something "new" to push.) After pushing the "new" commit, tests restart.

In your case, just `git rebase -i master`, drop the second commit, and force push. Tests should run again and will probably succeed.

**Comment by ajdapretnar** [comment]
I think @priyanshu-bisht was referring to my request for a test. :)
This is a simple assert. You create a small dataset, where one document has no tokens. Then you test with
`np.testing.assert_array_equal(data.X.flatten(), [x, y, z])`
where x, y, z are the expected results of the dataset for "Per cent unique words". One of those has to be 0 (or `np.nan`, depending on your solution).

**Comment by janezd** [comment]
@ajdapretnar, I'm sorry, I overlooked your comment.

By the way, I believe that with no tokens, the percentage of unique ones is not 0, but n/a, which is more nan-ish than 0-ish. (If there are no tokens, I'd say that all of them are unique, so the percentage is actually 1, not 0. :)

**Comment by ajdapretnar** [comment]
> By the way, I believe that with no tokens, the percentage of unique ones is not 0, but n/a, which is more nan-ish than 0-ish.

Yes, I agree. Nans make more sense.

**Comment by priyanshu-bisht** [comment]
@janezd 
okay I will rebase it after adding the tests :)

**Comment by priyanshu-bisht** [comment]
@ajdapretnar 
Hey does this looks okay?

getting one empty doc
```ruby
    def _create_one_empty_data(self) -> None:
        """
        Creat a simple dataset with 4 documents with 1 document empty . Save it to `self.one_empty_corpus `.
        """
        metas = np.array(
            [
                "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                "",
                " a porta\tleo. Duis vitae ultrices massa. Mauris ut pulvinar a",
                "tortor. Class (aptent) taciti\nsociosqu ad lit1ora torquent per",
            ]
        ).reshape(-1, 1)
        text_var = StringVariable("text")
        domain = Domain([], metas=[text_var])
        self.one_empty_corpus = Corpus(
            domain,
            X=np.empty((len(metas), 0)),
            metas=metas,
            text_features=[text_var],
        )
```
And computing the features
```ruby
    def _compute_one_empty_feature(self, feature_name: str, value: str = "") -> Corpus:
        """
        Send `self.one_empty_corpus` to widget, set statistic which need to be computed,
        run the computation, and return widget output.

        Parameters
        ----------
        feature_name
            The name of the statistic, only one statistic is set
        value
            The value if statistic need it.

        Returns
        -------
        Resulting corpus.
        """
        self.send_signal(self.widget.Inputs.corpus, self.one_empty_corpus)
        self.wait_until_finished()
        self._set_feature(feature_name, value)
        self.widget.apply()
        self.wait_until_finished()
        res = self.get_output(self.widget.Outputs.corpus)
        self.assertTupleEqual((len(self.corpus), 1), res.X.shape)
        return res
```

and assertion

```ruby
    def test_per_cent_unique_words(self):
        """ Test per-cent unique words statistic """
        data = self._compute_features("Per cent unique words")
        np.testing.assert_array_almost_equal(
            data.X.flatten(), [1, 1, 0.909091, 1]
        )
        
        #added this code
        data = self._compute_one_empty_feature("Per cent unique words")
        np.testing.assert_array_almost_equal(
            data.X.flatten(), [1, np.nan, 0.909091, 1]
        )
        
        self.send_signal(self.widget.Inputs.corpus, None)
        self.assertIsNone(self.get_output(self.widget.Outputs.corpus))

```

**Comment by ajdapretnar** [comment]
It looks ok, it is just very elaborate.

I would just override self.corpus with:
self.corpus[1][-1] = ""
setting the second text to an empty string.
Then run
data = self._compute_features("Per cent unique words")
and test with assert.

3 lines of code for the same effect. :)

**Comment by priyanshu-bisht** [comment]
@ajdapretnar 
Yes but wouldn't it change the corpus for all the other tests too?

I guess then have to change it back after assertion, right?

**Comment by ajdapretnar** [comment]
No, a new instance is created for each test. It only affects the function where you change the corpus.

**Comment by priyanshu-bisht** [comment]
@ajdapretnar 
ok thanks, I didn't know that

<code>owstatistics.py</code>
```
    def perc_unique(tokens: str):
        callback()
        if not tokens:
            return np.nan
        return len(set(tokens)) / len(tokens)
```
<code>test_owstatistics.py</code>
```
    def test_per_cent_unique_words(self):
        """ Test per-cent unique words statistic """
        data = self._compute_features("Per cent unique words")
        np.testing.assert_array_almost_equal(
            data.X.flatten(), [1, 1, 0.909091, 1]
        )

        self.corpus[1][-1] = ""
        data = self._compute_features("Per cent unique words")
        np.testing.assert_array_almost_equal(
            data.X.flatten(), [1, 1, 0.909091, np.nan]
        )
        
        self.send_signal(self.widget.Inputs.corpus, None)
        self.assertIsNone(self.get_output(self.widget.Outputs.corpus))
```

I hope so its correct now.
And thanks for being patient with me, I'm new to this stuff so I don't know these little things as you and @janezd mentioned.

**Comment by ajdapretnar** [comment]
No worries! I am glad you took the time to get to know Orange and submit a PR!

It looks ok, just one little thing. You have made the second document empty. So your assert has to be `[1, np.nan, 0.909091, 1]` instead of `[1, 1, 0.909091, np.nan]`.

If you run the test, it should pass. It is a good practice to first write the test that fails with the bug, then make a fix where the test passes.

**Comment by priyanshu-bisht** [comment]
@ajdapretnar 
okay dude fixed it, sorry for that.

**Pull request merged**
