### PR TITLE
[FIX] TweetProfiler: Return None When Servers Down

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue
Server call can return None when servers are down which causes the code to crash.

##### Changes
`tweetProfiler.transform` returns None when something goes wrong.

### CODE REVIEW

**Comment by nikicc** [comment]
Resolves https://sentry.io/biolab/orange3-text-bl/issues/204513241/

**Comment by ajdapretnar** [comment]
Could we add an informative warning such as 'Servers unavailable at the moment. Please try later.' or sth similar?

**Comment by nikicc** [comment]
We already raise the error message which is almost identical to your suggestion. It happens in `server_call` method.

**Comment by ajdapretnar** [comment]
Ok, then I just don't know how to test this. 😄

**Comment by nikicc** [comment]
It's a bit tricky. Try to disconnect from the internet while the TweetProfiler is running. You should get the error message.

**Comment by ajdapretnar** [comment]
Hmmm, tried it a couple of times and each time Python crashes when I disconnect. No error. 😞 The progress bar was between 10% and 50% each time.

**Comment by nikicc** [comment]
> Hmmm, tried it a couple of times and each time Python crashes when I disconnect. No error. 😞 The progress bar was between 10% and 50% each time.

Can you try again? It looks like the `requests.post` did not have any timeout and was waiting forever. Should be fixed now.

**Pull request merged**
