### PR TITLE
[FIX] OWPreprocess: commit automatically for N-grams

### LINKED ISSUE #336: Preprocess Text: N-grams doesn't commit automatically
##### Text version

0.3.0

##### Orange version

3.10.dev

##### Expected behavior
Changes are committed automatically when 'Commit automatically' is ticked.

##### Actual behavior
When changing N-grams range, changes aren't committed by changing parameters or by pressing enter. One has to click Commit manually or turn off and on the N-gram section.

### PR DESCRIPTION
**Pull request by matejklemen**
##### Issue
Fixes #336.

##### Description of changes
Changed the connection of signal so that it is consistent with how it's done in `FilteringModule` (the other place where `RangeWidget` is used).

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This works well! Thanks!
Could you perhaps add some tests? 🤔 
I will restart Travis, because it doesn't seem to exit on this issue.

**Comment by matejklemen** [comment]
Sorry for the late reply - I'll try to figure something out for tests when I find some time

**Comment by ajdapretnar** [comment]
Sure, no worries. 👍 
Could you also rebase to latest master so that the tests would pass? We fixed a couple of things by now.

**Comment by s-alexey** [comment]
It seems like there is a problem with `RagneWidget.valueChanged` signal as well. I think we could drop it as it no longer used.

**Comment by ajdapretnar** [comment]
I am sorry @matejklemen for the mess I have made today. Especially messing with your branch. Apologies! 🙏 

I made a new PR with your commit in #436. If tests pass, I will merge it. You remain the author of the code.

Thank you for this fix!

**Comment by ajdapretnar** [comment]
Continued in #436.

**Pull request closed without merging**
