### PR TITLE
Naive_Bayes_Classifier_For_Sentiment_Analysis

### PR DESCRIPTION
**Pull request by cicco94**
##### Description of changes
This code provide another Sentiment Analysis resource based on the Naive Bayes Classification. It will add the "isPositive" column with 0 or 1 value for each sentence

Capture3

Capture0

Capture

Capture2

Capture5

##### Next changes
In the next MR will be possible choose if and how setting train&test set

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by cicco94** [comment]
here the flow to test it (as in the attachments):

[test_naiveBayes_widget.zip](https://github.com/biolab/orange3-text/files/6199899/test_naiveBayes_widget.zip)

**Comment by ajdapretnar** [comment]
@cicco94 Thank you for submitting a pull request. We appreciate it. We do not wish to discourage you from submitting, but I have a couple of reservations here.
1. You are including a data set in the PR and training the model in the widget itself. I don't think this is really good practice.
2. The method is language-specific **and** domain-specific, which means it is applicable only for a very specific task.
3. The procedure you are proposing can actually be done in Orange itself, with Naive Bayes classifier and the movie reviews data set. I don't think something that can already be done in Orange warrants inclusion in a widget.

**Comment by cicco94** [comment]
closing because of point 3 of @ajdapretnar comment :)

**Comment by ajdapretnar** [comment]
I just wanted to add how to do it in Orange.
I used https://www.cs.cornell.edu/people/pabo/movie-review-data/. It takes a while to load.
This would be the workflow:

Screen Shot 2021-03-25 at 10 45 22

**Pull request closed without merging**
