### PR TITLE
OWStatistics: update GUI

### LINKED ISSUE #733: Statistics: add better buttons
**Is your feature request related to a problem? Please describe.**
Statistics suffers from the same problem that used to pester Merge Data: https://github.com/biolab/orange3/pull/5539

**Describe the solution you'd like**
Change + and x buttons to be the same as in Merge Data.

**Describe alternatives you've considered**
/

**Additional context**
image

### PR DESCRIPTION
**Pull request by ajdapretnar**
##### Issue

Fixes #733. 

##### Description of changes
Make buttons the same as in Merge Data.
Put Apply button to buttonsArea.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@ajdapretnar can you rebase it on master?

**Comment by ajdapretnar** [comment]
Done.

**Comment by PrimozGodec** [comment]
Thanks it looks better now. :)

**Pull request merged**
