### PR TITLE
[FIX] NLTK_data: Download to Application Data Instead of Home

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue
NLTK data was downloaded to home dir which could cause problems when 'nltk_data' file was present. https://sentry.io/biolab/orange3-text-bl/issues/204394326/

##### Changes
Download nltk_data to Orange's application data location instead.

### CODE REVIEW

**Comment by nikicc** [comment]
https://sentry.io/biolab/orange3-text-bl/issues/204394326/

**Comment by ajdapretnar** [comment]
I have no idea how to test this. 😕

**Comment by nikicc** [comment]
Delete `nltk_data` folder in your home directory and then check if preprocessing, language stopwords, etc. work. If everything seems to work then we are probably ok.

You can also check `/Library/Application Support/Orange` and see if `nltk_data` folder is there.

**Comment by ajdapretnar** [comment]
Um, with this version (after running pip install -e . and python -m Orange.canvas), I can't even see Preprocess Text. Before that the widget crashed. I have no /Library/Application Support/Orange folder at all...... 😢

**Comment by nikicc** [comment]
> Um, with this version (after running pip install -e . and python -m Orange.canvas), I can't even see Preprocess Text. 

That's as expected. Currently Preprocess Text rely on NLTK data and hence when it is missing cannot function. This couldn't have worked before either, I think.

> I have no /Library/Application Support/Orange folder at all...... 😢

Sorry about that. It's actually `~/Library/Application Support/Orange`.

**Pull request merged**
