### PR TITLE
[FIX] OWWordCloud: scale visualization

### LINKED ISSUE #347: Word Cloud: scale visualization
##### Text version

0.3.0

##### Orange version

3.14.dev

##### Expected behavior
Word Cloud scales visualization once everything is displayed in the window.

##### Actual behavior
Word Cloud stays small, only white space increases.

##### Steps to reproduce the behavior
wordcloudsize

### PR DESCRIPTION
**Pull request by robertcv**
##### Issue
Fixes #347 
##### Description of changes
Scale font size in proportion to the window size.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by robertcv** [comment]
@ajdapretnar Could you please check if the visualizations looks ok. Perhaps we could find a better scaling factor.

**Comment by ajdapretnar** [comment]
I like it. The only thing that could be fixed as well is all the redundant white space around the cloud. I think it is excessive. Can you make it smaller? This way the scaling would look better, too.

**Comment by ajdapretnar** [comment]
Hm. I get redundant white space for all corpora... 🤔  It's not such a big deal, but if you have any idea how to get rid of so much white space, it'd be great. If not, I can merge as it is.

screen shot 2018-10-29 at 12 17 13
screen shot 2018-10-29 at 12 17 18

**Comment by ajdapretnar** [comment]
Oh, perhaps this could be a part of this issue as well, since scaling depends on the window size. I don't like the fact that one can shrink the widget all the way to the control area. Perhaps some minimum size is in order here. I'll let you decide on this one. :)

**Pull request merged**
