### PR TITLE
[ENH] Document embedders: additional languages

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

Document embedders currently support only three languages.

##### Description of changes
With this PR we add support for 28 additional languages.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
I tested all embedders and it seems they work.

**Comment by ajdapretnar** [comment]
We have English as a default in most places. Probably it should be here as well? (I know, we are forcing the lingua franca, but even Orange comes in English only)

**Comment by ajdapretnar** [comment]
The rest works well, btw.

**Comment by PrimozGodec** [comment]
Uf completely forgot about that. English should be default now.

**Pull request merged**
