### PR TITLE
CorpusViewer: Support Table, search in Search features

### PR DESCRIPTION
**Pull request by nikicc**
* CorpusViewer adopted for Tables. Instead of searching in `corpus.documents` it searches in `Search features` and it displays `Display features`.
* CorpusViewer skip Bag-of-Words features.
* LoadCorpus allows attributes and class_vars for mining.

### CODE REVIEW

**Comment by nikicc** [comment]
@kernc, @ajdapretnar any volunteers to review this? We should release a new version soon and this would be nice to include.

**Comment by ajdapretnar** [comment]
@nikicc I will. :+1:

**Comment by ajdapretnar** [comment]
@nikicc The GUI seems nicer and more user-friendly.
However, there's an issue with regex filter. When I'm typing regex into the line, it seems like it's constantly checking the validity of regex. So if I make a typo or I'm not even done constructing the regex, it crashes (e.g. try backward slash and only one parenthesis).

**Comment by nikicc** [comment]
Hmmm ... yes, because now we only accept regexes and this is an invalid one. I will add a checkbox to disable regex search.

**Comment by ajdapretnar** [comment]
@nikicc How about filtering only on pressing Enter? I reckon it might be annoying to constantly check and uncheck the box. Or perhaps simply filtering only if regex is valid, otherwise simply not filter anything?

**Comment by nikicc** [comment]
> @nikicc How about filtering only on pressing Enter?

This could be an option, however it is not as interactive. I think until constant re-search will be to slow, maybe we should keep it.

> I reckon it might be annoying to constantly check and uncheck the box.

Why would you constantly check and uncheck? If you want regex, you just check it, if not it is already unchecked. If you checked regex and it is currently invalid since you are in the middle of typing it should not fail. IMHO it should just let you know that the regex is not complete.

> Or perhaps simply filtering only if regex is valid, otherwise simply not filter anything?

This disables the option for simple search. I think we should definitely support simple search. Most users are probably not using regex anyway. We should not force someone who whats to search for parenthesis to go figure out what is the regular expression for it. I think we should have two different modes, simple and regex.

I recommend opening an issue for this and handle this in an other PR? Since this one does not target regex search and already contains some minor bug-fixes 🙈

**Comment by ajdapretnar** [comment]
> If you checked regex and it is currently invalid since you are in the middle of typing it should not fail.

But that's exactly what's happening. It is failing in the middle of typing regex.

**Comment by nikicc** [comment]
> But that's exactly what's happening. It is failing in the middle of typing regex.

Yes, but we should fix it. I was just arguing that this bug should not be the reason to disable interactive search and force users to press Enter.

**Comment by ajdapretnar** [comment]
@nikicc Aaaaa, ok. :smile: Agree on that one. I can go through the widget again once this is fixed. :+1:

**Comment by kernc** [comment]
> Or perhaps simply filtering only if regex is valid, otherwise simply not filter anything?

> We should not force someone who wants to search for parenthesis to go figure out what is the regular expression for it.

We don't distinguish between these two modes now, do we? Few, if any, indexing engines support search by non-alnum characters. The user is trained. :stuck_out_tongue: If the regex compilation fails, I vote for just not doing anything (particularly, don't change the previous filtering).

**Comment by nikicc** [comment]
> If the regex compilation fails, I vote for just not doing anything (particularly, don't change the previous filtering).

That was an easy fix 😄 @ajdapretnar does this works for you?

**Comment by ajdapretnar** [comment]
@nikicc Yup. :) Can I press the lovely 'Merge'?

**Comment by nikicc** [comment]
@ajdapretnar if you did not find anything else broken I think you can 😄

**Pull request merged**
