### PR TITLE
Icon for text statistics widget.

### PR DESCRIPTION
**Pull request by larazupan**

### CODE REVIEW

**Comment by nikicc** [comment]
@markotoplak we do not have the widget yet, but can you check the icon to this can be merged?

**Comment by kernc** [comment]
Where the widget?

**Comment by ajdapretnar** [comment]
You can make it, it would be really great!

**Comment by kernc** [comment]
@markotoplak Please use [Squash and Merge](https://help.github.com/articles/merging-a-pull-request/#merging-a-pull-request-on-github).

**Pull request merged**
