### PR TITLE
[FIX] OWNYT: Improve Behaviour when No Internet Connection

### LINKED ISSUE #182: urllib.error.URLError:  <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
https://sentry.io/biolab/orange3-text-bl/issues/204513215/

```
urllib.error.URLError:  <urlopen error [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。>
(15 additional frame(s) were not displayed)
...
  File "D:\Anaconda3\lib\urllib\request.py", line 466, in open

    response = self._open(req, data)
  File "D:\Anaconda3\lib\urllib\request.py", line 484, in _open

    '_open', req)
  File "D:\Anaconda3\lib\urllib\request.py", line 444, in _call_chain

    result = func(*args)
  File "D:\Anaconda3\lib\urllib\request.py", line 1282, in http_open

    return self.do_open(http.client.HTTPConnection, req)
  File "D:\Anaconda3\lib\urllib\request.py", line 1256, in do_open

    raise URLError(err)
```

### LINKED ISSUE #184: http.client.BadStatusLine:  ''
https://sentry.io/biolab/orange3-text-bl/issues/204513206/

```
http.client.BadStatusLine:  ''
(9 additional frame(s) were not displayed)
...
  Module "urllib.request", line 1202, in http_open

    return self.do_open(http.client.HTTPConnection, req)
  Module "urllib.request", line 1177, in do_open

    r = h.getresponse()
  Module "http.client", line 1172, in getresponse

    response.begin()
  Module "http.client", line 351, in begin

    version, status, reason = self._read_status()
  Module "http.client", line 321, in _read_status

    raise BadStatusLine(line)
```

### PR DESCRIPTION
**Pull request by nikicc**
A few fixes regarding OWNYT:
* Catch URLErrors; fixes #182.
* Catch BadStatusLine errors; fixes #184.
* Show an error message when there is no internet connection.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Is there a particular way to test this or will random clicking on NYTimes do?

**Comment by nikicc** [comment]
Yup, there is a particular way to test this. Disconnect from the internet just before you click OK button that checks your API key. It should not crash and the error message should be shown.

**Comment by ajdapretnar** [comment]
Yup, it works, but if I set the API, then turn off the internet connection and start Search, then it goes into 0%, stays there and cannot be stopped with Stop. Somewhat related to the issues.

**Comment by nikicc** [comment]
> Yup, it works, but if I set the API, then turn off the internet connection and start Search, then it goes into 0%, stays there and cannot be stopped with Stop. Somewhat related to the issues.

I hopefully fixed this now. Please, check again.

**Comment by ajdapretnar** [comment]
> Yup, it works, but if I set the API, then turn off the internet connection and start Search, then it goes into 0%, stays there and cannot be stopped with Stop. Somewhat related to the issues.
> I hopefully fixed this now. Please, check again.

I'm sorry, I don't think it works. 😔 I've put on NY Times, correct API, ran the query then turned off the WiFi. Stopped at some percent and didn't not report connection error. Only when I press stop it works. But perhaps that's the only way to do it without testing web connection every n seconds...

The API things work as reported in the commits.

**Comment by nikicc** [comment]
> I'm sorry, I don't think it works. 😔 I've put on NY Times, correct API, ran the query then turned off the WiFi. Stopped at some percent and didn't not report connection error. Only when I press stop it works. But perhaps that's the only way to do it without testing web connection every n seconds...

I see, sorry for that. Somehow it worked for me yesterday, but does not any more today. I also added 10s timeout as for tweet profiler. Hope this finally resolves the issue. Please check one more time 🙈

**Comment by ajdapretnar** [comment]
It works! 🎉

**Pull request merged**
