### PR TITLE
Widgets: Change imports to AnyQt

### PR DESCRIPTION
**Pull request by nikicc**

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Sorry, @nikicc, but it's not working for me. As far as I understood, simple `python corpus.py` should open Corpus widget for me, but the widget doesn't open (exit with 0 status though).
Also a rebase is probably necessary.

**Comment by nikicc** [comment]
@ajdapretnar maybe we misunderstood. The idea is that `python owcorpusviewer.py` should open the widget, not `python corpus.py`.

This PR changed imports to AnyQt instead of PyQt4 and it seems to work on for me on PyQt5. To test if all works ok also on PyQt4 (I guess you are still on PPyQt4, right?) I suggest you try to run all widgets from `orangecontrib/text/widgets` as standalone. They all should open without any errors regarding `AnyQt` import.

**Comment by ajdapretnar** [comment]
Yeah, running PyQt4. Misunderstood what I had to do, corpusviewer.py works well. As a matter of fact, all do, with the exception of wordenrichment.py, which doesn't have def main() function, so I reckon it doesn't run as standalone without it.

**Comment by ajdapretnar** [comment]
Should I merge or would you want to check this on my machine?

**Comment by nikicc** [comment]
@ajdapretnar if you checked I think we can merge 😄

**Pull request merged**
