### PR TITLE
Word Enrichment: Computing in a separate thread (with ConcurrentMixin)

### LINKED ISSUE #221: WordEnrichment Should Run in a Thread
##### Text version

0.2.4.dev

##### Expected behavior
WE runs in a thread. If it gets new input the current thread is killed and new one is started (like in topic modelling). This becomes quite annoying when you select documents by typing in corpusviewer.

##### Actual behavior
It runs in parallel.

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

#221 

##### Description of changes
Besides implementing the thread computation with ConcurrentWidgetMixin which fixes #221, this PR also:
- implements input and output info in a status bar
- adds better unit tests for a widget
- refactors a code a bit

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This a great PR. But I wouldn't be me if I didn't have any comments. 😬 
Cluster words and Selected words is not clear to me. Cluster words apparently are all words and selected are non-zero ones (so those that actually exist in the subset). I think it would make more sense to say 'Total words' and 'Words in subset' or sth similar. Or perhaps get rid of Cluster words?

I am slightly confused by '18 words on the output'. The tooltip then explains that 18 words have been found, but do we have another widget that shows computational results instead of the output? I could be confusing for the users.

On the same note: tree (i.e. found words) should not be selectable. It can confuse the user, too.

**Comment by ajdapretnar** [comment]
Perhaps a solution for the status bar would be introducing a new icon that would replace the output icon (say a lightbulb) and signify the result of the widget.

**Comment by PrimozGodec** [comment]
I change texts and disabled the selection.

> Perhaps a solution for the status bar would be introducing a new icon that would replace the output icon (say a lightbulb) and signify the result of the widget.

I will wait until we decide whether we implement this.

**Comment by PrimozGodec** [comment]
It should be finished now. @ajdapretnar can you check when you have time.

**Pull request merged**
