### PR TITLE
Document embedder handle skipped and long documents

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Issue

Hopefully fixes https://github.com/biolab/orange3-text/issues/571

In my case, the problem is that some documents are too long and we limit the maximum length of the document that can be sent to the server. In those cases, a runtime error is raised.

##### Description of changes
With this PR:
- we enable that only documents that re too long are skipped and that embedding process is not interrupted than before
- we add a signal to the widget that shows the skipped documents - similarly than in Image Embedding widget

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by alichoumane** [comment]
Thank you very much. Yes I think the problem was that some of my documents are too long. Once I filtered the texts of each document to keep only the top 100 tokens (in the Preprocess text widget), it works! 
How to try you modifications ? I am using the latest stable Orange data mining version, not the development version. Should I wait for the next update ?

**Comment by PrimozGodec** [comment]
@alichoumane we are also thinking about how to increase supported number o tokens. Currently, the user can embed documents with up to 17k tokens which are 20% of the average book with around 250 pages. 

> How to try you modifications ? I am using the latest stable Orange data mining version, not the development version. Should I wait for the next update ?

We will try to release a new version of Text add-on as soon as possible, but if you want to test it there are some options. If you installed Orange with the installer which is available on our website then the easiest way to install this version is:
1. Go to branch with the version from this pull request https://github.com/PrimozGodec/orange3-text/tree/embedder-runtime-error
2. Click on `code` button in the top right corner and then click on `Download ZIP`
3. Open Orange and go to Options>Add-ons
4. Grab downloaded ZIP from the second step and drop it in the Add-ons dialogue.
5. Click OK, it will install the version of text add-on with these changes

**Comment by alichoumane** [comment]
@PrimozGodec thank you very much!
I installed it, now it is making an internet error instead. It works for the top ~200 tokens, as before. Is this related to my internet connection?

**Comment by alichoumane** [comment]
@PrimozGodec Thank you very much ! It works now for larger documents (even if there is internet error that occurs lot of times when the extracted tokens list is too large).

**Pull request merged**
