### PR TITLE
Add Filewidget to OWLoadCorpus

### PR DESCRIPTION
**Pull request by s-alexey**

### CODE REVIEW

**Comment by nikicc** [comment]
This is great! I only have one minor comment before merging. I prefer the way buttons used to look before.

Before:
screen shot 2016-06-30 at 17 35 23
Now:
screen shot 2016-06-30 at 17 19 26

This might have something to do with the fact that we use `QPushButton` instead of `gui.button` that was used before. Could we still use `gui.button` or make this buttons nicer in some other way? Strangely this looks ok in Preprocess text widget that also uses `widgets.FileWidget`.

**Comment by s-alexey** [comment]
I will change the buttons' size, but here how they looked before on my laptop: 
image

**Comment by s-alexey** [comment]
@nikicc you can check it now

**Comment by nikicc** [comment]
This looks great! Merging 😄

**Pull request merged**
