### PR TITLE
Tweet Profiler Cleanup

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue

Various improvements of Tweet Profiler.

##### Description of changes
* Remove tokens verifications.
* Remove info box.
* Mark probabilities features as not hidden.
* Don't rerun with the same parameters.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Widget crashes with:
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nikicc** [comment]
Crap, I forgot to push the updated server code. Please check again, it should work now.

**Comment by ajdapretnar** [comment]
Yes, now it works.
However, I've noticed something in Tweet Profiler widget. When I use any dropdown and I don't select anything new (say my Attribute stays Text as it was before), the entire computation seems to be run again. Could you please check if this could be avoided?

**Comment by nikicc** [comment]
@ajdapretnar I added a simple check that prevents reruns with the same parameters.

Though, it would probably be better if `gui.comboBox` would have and option to prevent calling `callback` when the same value is selected.

**Comment by ajdapretnar** [comment]
> Though, it would probably be better if gui.comboBox would have and option to prevent calling callback when the same value is selected.

Agree. Something to discuss with Janez on a Friday. So far it works, so I'm merging.

**Pull request merged**
