### PR TITLE
Prettify NTY, Pubmed, Wikipedia icons

### PR DESCRIPTION
**Pull request by nikicc**
@ajdapretnar do you prefer these icons?

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Looks good to me! :grin:

**Comment by nikicc** [comment]
@ajdapretnar if you think this is an improvement over the previous state feel free to merge 😉

**Comment by ajdapretnar** [comment]
I totally would, but Blaž had some reservations regarding the icon-only style. His reasoning is that these widgets output corpus and should thus be represented with document icon. Perhaps @BlazZupan you can comment when you manage.

**Comment by nikicc** [comment]
> His reasoning is that these widgets output corpus and should thus be represented with document icon.

But then we should also adopt Twitter and Wikipedia to this style which would results in total six widgets based on the file icon?

OK, let's wait for Blaž.

**Comment by ajdapretnar** [comment]
> But then we should also adopt Twitter and Wikipedia to this style which would results in total six widgets based on the file icon?

Yes, that's my concern as well. It's too much. I guess we can also make an executive decision and go with big icons. One pro for this is Data Fusion add-on example.

**Pull request merged**
