### PR TITLE
[FIX] The Guardian, Twitter, NYT: Error credentials

### PR DESCRIPTION
**Pull request by jerneju**
##### Description of changes
try except block

##### Includes
- [X] Code changes
- [X] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-text-bl/issues/282422265/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-text-bl/issues/281293166/

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-text-bl/issues/279831959/

**Comment by nikicc** [comment]
@jerneju should we maybe fix `CredentialManager.__getattr__` to catch the error and then return an empty string?

This is fixing retrieving from CredentialManager. What about storing into it? Can the same thing happen there?

**Comment by jerneju** [comment]
@nikicc if we do not plan to show an error message in the future, then fixing `CredentialManager` is way better. Is there any widget where user really should be informed about this error?

**Comment by jerneju** [comment]
@nikicc I have finally done the test. It does raise an error when trying to store it.

**Comment by nikicc** [comment]
This is probably blocked on https://github.com/biolab/orange3/pull/2354 right?

**Comment by jerneju** [comment]
Closed in favor of https://github.com/biolab/orange3/pull/2354 .

**Pull request closed without merging**
