### PR TITLE
EmotionProfiler widget

### PR DESCRIPTION
**Pull request by nikicc**
Initial version of Emotion Profiler widget. We should probably replace the icon with something more similar to other icons.

### CODE REVIEW

**Comment by kernc** [comment]
> We should probably replace the icon

How about a simple smiley face: `☺` ?

**Comment by nikicc** [comment]
Yup, I changed the icon to a smiley and it seems much better 😄

**Comment by ajdapretnar** [comment]
It looks great! However, just a question. Should the widget not compute all three possible outputs beforehand and output whatever is selected instantaneously? Because even now, when changing between possible outputs, everything gets re-calculated every time. :/

**Comment by ajdapretnar** [comment]
One more thing. Are classes always binary? From what I see, I only get 1 yes per tweet, never more. Should we not have then an 6-valued class instead of 6 classes? I can think of pros and cons for both....

**Comment by nikicc** [comment]
> It looks great! However, just a question. Should the widget not compute all three possible outputs beforehand and output whatever is selected instantaneously?  Because even now, when changing between possible outputs, everything gets re-calculated every time. :/

I agree that this might be better for the user, but probably not for our server. If we would like to compute everything then we would need to run 6x as much computation (Ekman, Plutchik, POMS) x (Embeddings, Probabilities). At least for now — or until I do not finish with my unison models where running all at one will be cheaper — I recommend that we stick with the current solution.

**Comment by nikicc** [comment]
> One more thing. Are classes always binary? From what I see, I only get 1 yes per tweet, never more. 

Current models work in multi label setting. That is, we make a decision for each emotion independently of others, and nothing is stopping our models to say yes for all emotions at once.

> Should we not have then an 6-valued class instead of 6 classes? I can think of pros and cons for both....

I think we should leave the current models as they are and also add classifiers that work in multi class setting — I also have those 😉. This should be done at a server side, so it does not affect this PR.

**Comment by ajdapretnar** [comment]
Ok, let me know when things are ready to merge + I'd love a Python code snippet that creates a new variable from these classes and sets the value to highest probability emotion. :) Because ⭐️ coloring plots by class ⭐️.

**Comment by nikicc** [comment]
OK, I'll let you know when tests are added and this is ready to merge. As of coloring, I'll add multi class option soon.

**Comment by nikicc** [comment]
@ajdapretnar this finally has tests and is ready for one final check.

**Pull request merged**
