### PR TITLE
[MNT] Install PyQt on Travis to Enable Widget Tests

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue
PyQt was not yet installed on Travis.

##### Changes
* Install PyQt to enable widget tests.
* Run tests on PyQt5.
* Change `setup.py tests` to discover tests instead of hardcoding its location.

### CODE REVIEW

**Comment by nikicc** [comment]
@ajdapretnar with this #191 should run the tests.

**Comment by ajdapretnar** [comment]
@nikicc How do I properly test this? Apply the patch to #191 and run some command for testing?

**Comment by nikicc** [comment]
It's a bit tricky I'm afraid. You could take these changes, apply them into your PR and this should make your tests run OK. Though, I already tested this. I pinged @kernc to take a look, maybe he can review and/or merge.

**Comment by ajdapretnar** [comment]
Yeah, I thought it won't be simple. Because applying it to my PR would make it work, but then I would have to revert my branch and push again only what I had..... I'm too lazy to do this. 😁

**Comment by nikicc** [comment]
@kernc can you check again? We now use unittest discovery to find all tests under `orangecontrib.text` and hence also tests under `orangecontrib.text.widgets.tests` are run simply by `python setup.py test`.

**Comment by kernc** [comment]
Really nice solution, I love it!

**Comment by nikicc** [comment]
Do you think we can merge?

**Comment by kernc** [comment]
Of course! Was just waiting on Travis to start working again.

**Pull request merged**
