### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by nikicc**
Add example schemas.

### CODE REVIEW

**Comment by ajdapretnar** [comment]
@nikicc Is this still WiP?

**Comment by ajdapretnar** [comment]
@nikicc I added some workflow, you can check when you have the time.

**Comment by nikicc** [comment]
@ajdapretnar I have modified the schemes to include the new corrected documentation data sets names, renamed them so they appear in a more intuitive order and edited a few thing here and there.

Can you also provide a description for each of the schemes? Just don't forget to pull first before editing.

**Comment by ajdapretnar** [comment]
@nikicc Did you push the changes? Because I don't think I see them... 🙈

**Comment by nikicc** [comment]
> @nikicc Did you push the changes? Because I don't think I see them... 🙈

I think I did. As I remember I just amended them to your commit. If, after you pull, tutorials files have names starting with numbers (e.g. `10-text-preprocessing.ows`, `20-bag-of-words.ows`, etc.) then I believe you have all my updates.

**Pull request merged**
