### PR TITLE
[ENH] Topic Modelling: Output a Table of Word Representation in Topic Space

### LINKED ISSUE #278: Reference term LSA
##### Expected behavior

We would like to to measure coherence of uttered speech to questions or a reference term.

##### Actual behavior

So far,  there is no way of include such a reference term or sentence.

### PR DESCRIPTION
**Pull request by nikicc**
##### Issue

Fixes #278.

##### Description of changes
Add additional output of words representation in topic space.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
This is too cool! 👍 💪
I can even check topic representation in a Heat Map!

Just a reminder: you'd probably want to rename the output to something different. 😉

**Comment by nikicc** [comment]
> I can even check topic representation in a Heat Map!

Yup, and you can also cluster word and see which almost always co-occur inside documents.


> Just a reminder: you'd probably want to rename the output to something different. 😉

Sure thing.

**Comment by nikicc** [comment]
@ajdapretnar this is ready for some more testing. Just to be sure, can you also confirm, that the new output weights match the ones we give in the `selected topic` output?

**Comment by ajdapretnar** [comment]
This seems ok. I check some random words and they all seemed to have correct weight in both outputs.

I am merging.

**Pull request merged**
