### PR TITLE
OWNYT Refactoring

### PR DESCRIPTION
**Pull request by nikicc**
Complete refactor of OWNYT widget and scripting part. Changes include:
- Use OWWidget for API dialog windows.
- Store key with Credential Manager.
- Use OWConcurrentWidget so loading is done in a separate thread, support stopping either by stop button or by running a different query.
- Always download all features. Hence checking different text include features does not require another run; it just sets `corpus.text_features` accordingly.

### CODE REVIEW

**Comment by nikicc** [comment]
@ajdapretnar this is ready for some testing. Since some technical changes were introduced along the way so I would love if @kernc could also take a look.

**Comment by ajdapretnar** [comment]
@nikicc I tested it and I like the new implementation. However, I have two questions/issues.
1.) When I check features I want to include in my text_features, I always get word_count and article_type appended by default. I'm not sure I like this. To remove them one has to then use Select Columns - Corpus Viewer - BoW, which is a bit of a pain... Should they be in checkboxes like the rest of the features?
2.) There used to be a feature called 'country', which was great for GeoMap widget. Now it's gone and I miss it. Is there a chance to include it back in the results?
Thanks!

**Comment by nikicc** [comment]
@ajdapretnar:

1.) This was an attempt to clean the mess we had before. IMO Text includes should only target StringVariables. Any other features can be used as they are and there is no need to add them to Text includes (though this is supported). Hence we probably shouldn't add them to checkboxes. But we could move them to metas?

2.) I added locations; it was removed by mistake. Along the way I discovered that keywords are very nicely annotated and they also provide Persons, Organisations, Creative Works and Subject keywords. So I added them as well.

**Comment by ajdapretnar** [comment]
> Any other features can be used as they are and there is no need to add them to Text includes (though this is supported). Hence we probably shouldn't add them to checkboxes. But we could move them to metas?

Yes, I agree they shouldn't be in 'Text includes'. Perhaps metas could be sensible at this point - at least I don't see a better place for them. I just think they shouldn't be a feature by default, but one should still be able to use them if required at some point (can you predict word count based on content and section tag 😁 ).

Big plus for keywords, they're awesome!

**Comment by nikicc** [comment]
@ajdapretnar they should be in metas now 😄

**Pull request merged**
