### PR TITLE
manifest: update source dist files

### PR DESCRIPTION
**Pull request by JakaKokosar**
##### Issue
Some of the files were missing from source distribution. 

##### Description of changes
Update MANIFEST so that it includes missing files.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by JakaKokosar** [comment]
I intentionally left out files related to the documentation. Some projects include them and others don't. I don't know what is right here. What do you think, @ajdapretnar?

**Comment by ajdapretnar** [comment]
I am honestly confused as to what MANIFEST is for. If you could explain perhaps I can have an opinion on including doc files. 😅

**Comment by JakaKokosar** [comment]
It specifies files that will be included in the source distribution of python project.

https://packaging.python.org/guides/using-manifest-in/

**Comment by ajdapretnar** [comment]
Tests are failing.
The doc test fails for an unknown reason. When building the docs locally, they pass. Also, the indentations are ok.
The 3.21 I am fixing as we speak. It is ugly, but until we support 3.21, it has to be there.

**Comment by ajdapretnar** [comment]
> It specifies files that will be included in the source distribution of python project.

Yeah, then I think it should.

**Comment by ajdapretnar** [comment]
#511 should fix the second fail. No idea why the first happens. Perhaps we merge 511, rebase and re-run tests.

**Pull request merged**
