### PR TITLE
Unify add-on descriptions

### PR DESCRIPTION
**Pull request by rokgomiscek**
##### Issue
Implements https://github.com/biolab/orange3/issues/4850

##### Description of changes
Unify add-on descriptions.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
Can be merged after https://github.com/biolab/orange3-text/pull/545 is merged

**Comment by PrimozGodec** [comment]
Under the feature section I would add something like (feel free to write this differently):
- Discover topics in the text
- Compute document statistics
- Visualize frequent words in the word cloud
- Find words that enrich selected documents

@ajdapretnar do you have anything to add or change here?

**Comment by ajdapretnar** [comment]
Thanks @PrimozGodec, looks good. I would just prefer to unify descriptions. We either have all second person verbs or third person verbs (embeds, load...?).

I propose second person. And have it with a capital at the beginning. :)

**Comment by PrimozGodec** [comment]
@ajdapretnar if you agree with the description merge this PR.

**Pull request merged**
