### PR TITLE
Remove format_summary_details

### PR DESCRIPTION
**Pull request by rokgomiscek**
##### Issue
Tests failed

##### Description of changes
Removes format_summary_details and replaces with format_summary_details from Orange

##### Includes
- [X] Code changes
- [x] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
You need to set minimum Orange version, too. :)

**Comment by rokgomiscek** [comment]
It has already been set in a previous PR to 3.25.

**Comment by ajdapretnar** [comment]
You're right. Sorry. 🙈

**Comment by PrimozGodec** [comment]
Can be merged after https://github.com/biolab/orange3-text/pull/546 is merged.

**Pull request merged**
