### PR TITLE
OWTwitter Search by Author using Timelines

### PR DESCRIPTION
**Pull request by nikicc**
Refactor of OWTwitter. New features:
* Use user_timeline to obtain tweets older than two weeks.
* Refactoring to OWConcurrentWidget.
* Reorder GUI a bit.

### CODE REVIEW

**Comment by nikicc** [comment]
@ajdapretnar this is ready for some more testing.

**Comment by ajdapretnar** [comment]
Please add 'Content' as default text feature.
Also Report functionality needs fixing (while we're at it). It should report on:
- query (by) author/content (e.g. Barack Obama by Author)
- language with full name (English, not en)
- fix tweet count (now broken)

Everything else works well for me. Even new lines aren't a problem anymore, which is such a relief!

**Comment by nikicc** [comment]
@ajdapretnar can you check again?

**Comment by nikicc** [comment]
Resolves https://sentry.io/biolab/orange3-text-bl/issues/204513245/

**Pull request merged**
