### PR TITLE
New folders and images for documentation

### PR DESCRIPTION
**Pull request by ajdapretnar**

### CODE REVIEW

**Comment by nikicc** [comment]
What's the reason for copying icons? Could we somehow link from documentation to `orange3-text/orangecontrib/text/widgets/icons/` instead of having two copies?

**Comment by ajdapretnar** [comment]
@nikicc Ah, sure! If you can figure out how to generate icons from svg in the documentation, you're more than welcome! :smile: I only copied what I did in the core Orange, which was create .png icons and include them in the docs by simply calling them. Hashtag cheating.

**Comment by nikicc** [comment]
> I only copied what I did in the core Orange, which was create .png icons and include them in the docs by simply calling them.

I don't see them in docs. Are they just here so when we will write the documentation for text they will already be prepared?

**Comment by ajdapretnar** [comment]
@nikicc Here's an [example](https://github.com/biolab/orange3/tree/master/doc/visual-programming/source/widgets/data/icons). Yes, I only copied them here for future use (and so @cheral and @s-alexey can use these folders for their documentation). All the docs in core Orange use these png icons for simplicity. I absolutely don't object to generating them from .svg, but I have no idea how to do it.

**Comment by nikicc** [comment]
I didn't noticed at first that they are png and I thought that you just made an other copy of svg.

**Pull request merged**
