### PR TITLE
[FIX] Twitter: adapt to APIv2

### PR DESCRIPTION
**Pull request by PrimozGodec**
##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
There are some things that need to be fixed here:

1. When opening the widget, it already contains the query "orange". Is this intended? I was hoping more for a placeholder than an actual pre-set query.
2. I enter the bearer token and run the query with the default settings. Nothing happens. The search is complete, but there is no output.
3. I then changed the language to English. Ran the search. The widget crashes with:
```
Traceback (most recent call last):
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 591, in _on_task_done
    super()._on_task_done(future)
  File "/Users/ajda/orange/orange3/Orange/widgets/utils/concurrent.py", line 547, in _on_task_done
    self.on_exception(ex)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owtwitter.py", line 278, in on_exception
    raise ex
  File "/Users/ajda/.pyenv-x86/versions/3.9.10/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/widgets/owtwitter.py", line 37, in search
    return api.search_content(
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/twitter.py", line 154, in search_content
    corpus, count = self._fetch(build_query(), max_tweets, callback=callback)
  File "/Users/ajda/orange/orange3-text/orangecontrib/text/twitter.py", line 215, in _fetch
    for i, response in enumerate(paginator):
  File "/Users/ajda/.pyenv-x86/versions/py3.9/lib/python3.9/site-packages/tweepy/pagination.py", line 98, in __next__
    response = self.method(*self.args, **self.kwargs)
  File "/Users/ajda/.pyenv-x86/versions/py3.9/lib/python3.9/site-packages/tweepy/client.py", line 907, in search_recent_tweets
    return self._make_request(
  File "/Users/ajda/.pyenv-x86/versions/py3.9/lib/python3.9/site-packages/tweepy/client.py", line 118, in _make_request
    response = self.request(method, route, params=request_params,
  File "/Users/ajda/.pyenv-x86/versions/py3.9/lib/python3.9/site-packages/tweepy/client.py", line 88, in request
    raise BadRequest(response)
tweepy.errors.BadRequest: 400 Bad Request
There were errors processing your request: missing EOF at '-' (at position 10)
```
4. After the crash, the search doesn't stop. The button resets to Search, but the progress bar is still running.
5. When the crash happens, a standard Orange error window opens. The major issue here is that the bearer token is also displayed. It is also probably sent together with the error message, if the user reports it. This should not happen.

**Comment by ajdapretnar** [comment]
Trying to download tweets from Orange, I get two errors:
With @OrangeDataMiner
```
Api error (400 Bad Request
There were errors processing your request: no viable alternative at input '@OrangeDataMiner' (at position 6))
```

With OrangeDataMiner
`Api error ('NoneType' object is not iterable)`

Before there was a check that every author search had to start with @, if I am not mistaken, otherwise an error would appear.

**Comment by PrimozGodec** [comment]
@ajdapretnar I hope it is done now. :P If you find any other case to cower I can add that.

**Comment by ajdapretnar** [comment]
I found some small issues, but I would not like to further block this great fix, so I'll merge and open another issue.

**Pull request merged**
