### PR TITLE
Preprocess: add modules

### PR DESCRIPTION
**Pull request by s-alexey**

### CODE REVIEW

**Comment by nikicc** [comment]
- [ ] Even if I set ngrams range from 2 to 2 in the widget on output the `corpus.ngrams_range` is set to (1, 1).

**Comment by nikicc** [comment]
- [ ] POS tags do not seem to be stored properly. In the widget I have selected the first tagger but on the output I get `corpus.pos_tags=None`.

**Comment by s-alexey** [comment]
Are there other issues and/or suggestion?

**Comment by nikicc** [comment]
> Are there other issues and/or suggestion?

@s-alexey not regarding n-grams and POS that I would currently know of.

There are, however, some other ideas related to this widget. If you would like to tackle any of them we  should talk.

**Comment by nikicc** [comment]
We broke something by merging #103. Can you please rebase?

**Comment by nikicc** [comment]
I merged this manually (5dea148b74bd11b1fdb9d321fc13cafaa1d0c22b) but it seems like I messed something up that prevented this to automatically close.

**Comment by ajdapretnar** [comment]
@s-alexey @nikicc This needs some tweaking.

1.) POS tags don't disappear from view, when I turn off POS tagger in Preprocess widget. I can still see POS tags in Corpus Viewer regardless.

2.) POS tagger runs tagging again just when turning the option on or off. Caching preferred.

**Pull request closed without merging**
