### PR TITLE
Concordance Fixups

### PR DESCRIPTION
**Pull request by nikicc**
Changes:
- Show info immediately when corpus is on input and do not wait till the word is present.
- Rename `width` attribute to `context_width` to enable Warnings to work.
- Enable Concordances to accept word on input (e.g. one can click on a word in wordCloud and observe its neighbourhood in concordances)

### CODE REVIEW

**Comment by ajdapretnar** [comment]
It's a little slow, but I'm not sure why. I've checked the code and it looks like nothing major changed... Hm.... 🙈

**Comment by nikicc** [comment]
You mean that it became slower than before on the same data?

**Comment by ajdapretnar** [comment]
> You mean that it became slower than before on the same data?

Well, I didn't time it, but it seems to be slower.

**Comment by nikicc** [comment]
I don't see how these changes could have slowed anything down. I'm not touching parts related to calculation where the majority of the time is spent. If you think it is slower now than before then we should time it.

**Pull request merged**
