### PR TITLE
[FIX] Preprocess Text: set highest absolute frequency

### LINKED ISSUE #669: Preprocess Text: set highest absolute frequency
**Is your feature request related to a problem? Please describe.**
Before revamping Preprocess Text, it was possible to set a combination of absolute and relative frequency. For example, removing only the tokens that appear in less than 5 documents (5 and 1.0). The first number was an integer and thus considered and absolute, while the second was a float and considered a relative (up to all the documents). Currently, one cannot remove only tokens that appear in less than 5 documents, because the default maximum is 10 and maximal maximum is 10000 (so if one has 10001 documents it cannot say "up to all documents").

**Describe the solution you'd like**
Enable filtering only the tokens that appear in less then N documents.
One could achieve this by setting the default maximum to the number of the documents. 🤷‍♀️ 

**Describe alternatives you've considered**
Having the filter set up as before.

**Additional context**
/

### PR DESCRIPTION
**Pull request by noahnovsak**
##### Issue
Fixes #669

##### Description of changes
Changes the behaviour of absolute frequency filter to return no upper cutoff point when the values of both boxes are equal.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@needNewUsername, was this PR closed by mistake?

**Comment by needNewUsername** [comment]
Yes, i thought it had been dealt with, but I now remember I was waiting for @ajdapretnar to check if this is the type of solution we are looking for, and make sure it doesn't break anything else.

**Comment by ajdapretnar** [comment]
There are some issues with the spin box, unfortunately.

If I set `min=2` and `max=max`, the results are ok.
Then I increase `min` to 3. The spin box value of `max` changes to 3 as well (visually), but the output is really `max`.
The spin box also allows me to pass `max` value smaller than `min` (i.e. `min=5`, `max=3`). There are a couple of options how to handle this (raising an error, reversing the values). But I think the nicest one is simply preventing the spin box to go below min value.

What do you think, @PrimozGodec?

**Comment by PrimozGodec** [comment]
@ajdapretnar I agree. I think that when the value of one spin changes the minimum/maximum values of the other one can be adjusted via `setMinimum/setMaximum`

**Comment by ajdapretnar** [comment]
This looks good to me, but I would sleep much easier if there was a test that would check this behavior. 😅 
For example passing:
- 5, None (check that it turns to max and that the output is ok)
- 5, 3 (check that it turns to max and that the output is ok)
- raising the final 3 to 6 and checking that it remains a 6 (not max)

**Comment by ajdapretnar** [comment]
I can tell you that for *deerwester* you should get:
- 1 word ("of")
- 1 word ("of")
- 1 word ("of")
- then perhaps try also 3-4, where you'd get "system, user, the, trees, graph".

**Comment by ajdapretnar** [comment]
As I need this quite urgently, I'll open another issue with a request for tests.

**Pull request merged**
