### PR TITLE
[FIX] guardian: fix failing tests

### LINKED ISSUE #354: Guardian: Fix failing tests on Travis
##### Text version

0.3.0

##### Orange version

3.15.dev

##### Expected behavior
Tests pass.

##### Actual behavior
Guardian tests is failing.

##### Additional info (worksheets, data, screenshots, ...)
Fix tests.

### PR DESCRIPTION
**Pull request by robertcv**
##### Issue
Fixes #354 
##### Description of changes
The `test` key has a limit we exceeded so the tests failed. This is resolved by requesting a developer  API key. Because it's a secret we add it to Travis as an environment variable (THE_GUARDIAN_API_KEY).

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by ajdapretnar** [comment]
Still not working. 😞 Any ideas?

**Comment by kernc** [comment]
Nah, The Guardian is [now fine](https://travis-ci.org/biolab/orange3-text/jobs/405689199#L1232).

**Comment by ajdapretnar** [comment]
Nope, I have restarted tests twice and they still fail with the same error: https://github.com/biolab/orange3-text/pull/357

**Comment by robertcv** [comment]
Yes, it's really strange because if I run Travis on my fork it works every time, but on the main repo, it dosesn't. This needs further investigation.

**Comment by kernc** [comment]
> Nope, I have restarted

Beside restarting, you need to rebase.

**Pull request merged**
