### PR TITLE
Concordances: add Send Report

### PR DESCRIPTION
**Pull request by jerneju**
##### Issue
No report.

##### Description of changes
Send report added.
Bug in `rowCount` fixed.

##### Includes
- [X] Code changes
- [ ] Tests
- [ ] Documentation

### CODE REVIEW

**Comment by nikicc** [comment]
This works for me, however, I have some concerns:
- I'm not sure whether removing the `parent.isValid()` is OK.
- We only report 100 lines, which might be too little for Concordances.

**Comment by nikicc** [comment]
@jerneju I modified the check for `parent.isValid()` a bit. Please check if all is still OK.

Perhaps, @ajdapretnar could you also take a look?

**Comment by jerneju** [comment]
It is still OK.

**Comment by ajdapretnar** [comment]
Atm I couldn't find (or think of) a case where this would fail, so I give it a 👍. Just one comment: perhaps we can remove tokens and types in report (do they make sense?) and instead add context length? I don't know how useful this is, it's just an idea.

**Comment by nikicc** [comment]
Then, perhaps, @ajdapretnar can you merge if all is well, since both @jerneju and I contributed?

**Comment by ajdapretnar** [comment]
Oh yes, of course! I merge boss!

**Comment by nikicc** [comment]
> Just one comment: perhaps we can remove tokens and types in report (do they make sense?) and instead add context length? I don't know how useful this is, it's just an idea.

I only spotted this now, but I agree with both comments 👍

**Pull request merged**
